### ISSUE TITLE
Dont know how to download or upload file via port 14000

### ISSUE THREAD

**Issue by YLonely** [uber/kraken#95]
Hi, i am a student who are interested in this project and i have already build a simple cluster on my mac through command 'make devcluster' and it runs so well , but right now i don't know how to download or upload normal files via port host.docker.internal:14000 as mentioned in [README.md](https://github.com/uber/kraken/blob/master/examples/devcluster/README.md). Should i use wget or curl ? But every time when i try to access this address it returns "404 page not found".
![image](https://user-images.githubusercontent.com/18494838/53963931-375fca80-4129-11e9-968e-121f8d17786b.png)
Looking forward to your reply. thx😄

**Comment by codygibb** [comment]
Usually you would use `docker pull` and `docker push` instead of curling endpoints manually (assuming you're working with images), but we also have endpoints for uploading / downloading arbitrary files via http. Check out the endpoint documentation here: https://github.com/uber/kraken/blob/master/docs/ENDPOINTS.md
